version: "3.8"

services:
  db:
      build:
        context: .
        dockerfile: ./db/deployment/db.Dockerfile
      restart: on-failure
      env_file:
        - ./db/config/db.dev.env
      expose:
        - "5432"
      ports:
        - "5432:5432"
      hostname: db
      volumes:
        - pgdata:/var/lib/postgresql/data/:cached

  backend:
    build:
      context: .
      dockerfile: ./backend/deployment/backend.Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./backend/config/backend.dev.env
    hostname: backend
    volumes:
      - ./backend/source:/source:cached
    depends_on:
      - db

volumes:
  pgdata: