version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/deployment/backend.Dockerfile
    restart: on-failure
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - ./backend/config/backend.dev.env
    hostname: backend
    volumes:
      - ./backend/source:/source:cached